# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en
  # outputs:
  #   home: [HTML, RSS, JSON]

# Uncomment the lines below to configure your website in a second language.
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  # outputs:
  #   home: [HTML, RSS, JSON]
  title: 李璇
  params:
    header:
      navbar:
        enable: true
        blox: "navbar"
        fixed_to_top: true
        show_search: true
        show_theme_chooser: true
        logo:
          text: "李璇"
  menu:
    main:
      - name: 关于我
        url: /
        weight: 10
      - name: 发表论文
        url: publication/
        weight: 25
      - name: 经历
        url: experience/
        weight: 40
      - name: 画廊
        url: gallery/
        weight: 55
