# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Hong Kong Baptist University'
    description: 'Academic site of Lewen Wang on computational and theoretical chemistry.'
    twitter: ''
  analytics:
    google_analytics: 'G-5FT9F48DR6'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: 'OsBBSuNlUCAThlPHszjlp0Mahpfmy6LBlHiVgf6jt-w'
    baidu: ''


# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: true
    show_theme_chooser: true
    logo:
      text: "Lewen Wang"

# Site footer
footer:
  copyright:
    notice: '© 2025 Lewen Wang'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: true
  privacy_pack:
    enable: false
